### PR TITLE
docs: Update README.md for docker compose usage

### PR DESCRIPTION
**Pull request by yuedanlabs**
usage for docker compose

maybe fix issues also for:
#526 
#649

### CODE REVIEW

**Comment by muety** [comment]
Agree to mentioning the ability to use Docker Compose, but I'd prefer not to bloat the README by putting a copy of [`compose.yml`](https://github.com/muety/wakapi/blob/master/compose.yml) there, instead of just referencing it. 

I'd simply say _"Alternatively, you can also use Docker Compose (`docker compose up -d`) for even more straightforward deployment"_ or sth.

**Comment by yuedanlabs** [comment]
> Agree to mentioning the ability to use Docker Compose, but I'd prefer not to bloat the README by putting a copy of [`compose.yml`](https://github.com/muety/wakapi/blob/master/compose.yml) there, instead of just referencing it.
> 
> I'd simply say _"Alternatively, you can also use Docker Compose (`docker compose up -d`) for even more straightforward deployment"_ or sth.

Yeah, that sounds reasonable.

**Comment by muety** [comment]
Will you change it accordingly?

**Comment by yuedanlabs** [comment]
> Will you change it accordingly?

yeah, I open a new pull for this.
#670

**Comment by yuedanlabs** [comment]
> Will you change it accordingly?

Yeah, the new update has been submitted.

**Pull request merged**
