### PR TITLE
Github Actions add a release for macOS

### PR DESCRIPTION
**Pull request by daief**
- merge multi platform release workflow files to a single release file
- support build macOS release

result link: <https://github.com/daief/wakapi/releases/tag/2.2.3-test3>
jobs: <https://github.com/daief/wakapi/actions/runs/2350071867>

### CODE REVIEW

**Review by YC — APPROVED** [review]

**Comment by YC** [comment]
Thanks for the improvement.

**Comment by muety** [comment]
Awesome contribution, thanks a lot! :pray:

Only a few, minor remarks, as you're already on it anyway (some are actually unrelated to your changes, but as you seem to have good expertise with GH actions, ...):
* [ ] Please name it "Build, test and release" or so, since the action does not only to releasing
* [ ] Sure sure if the "Enable Go 1.11 modules" step is still needed with Go 1.18, can you please check?
* [ ] Compress actions must only be run in case of a release
* [ ] Please only run on push to "master", not arbitrary branches

Optionally (if you're very keen):
* [ ] Replace deprecated https://github.com/actions/upload-release-asset action with https://github.com/softprops/action-gh-release
* [ ] Parallelize things by splitting up into different jobs (e.g. run unit tests, api tests and build in parallel, then run compression and release)

**Comment by daief** [comment]
My intention is just to support building a executable file of macOS. So I just edited it  based on your yml files.

Actually my GH actions knowledge is new and I do not konw anything about go so I can't answer "Enable Go 1.11 modules". Haha 😁 ... 

As for the otherthings of GH actions, I will try my best in the next few days.

**Comment by YC** [comment]
@muety Seems to be on by default in 1.16. 
https://maelvls.dev/go111module-everywhere/#go111module-with-go-116

**Comment by muety** [comment]
@daief Thank you anyway! Feel free to skip the "optional" change requests.

**Comment by daief** [comment]
I just updated. You can hava a check. Referred to these projects, it looks used to putting `test, build` into a single file.

- [ripgrep](https://github.com/BurntSushi/ripgrep/tree/master/.github/workflows)
- [UsTaxes](https://github.com/ustaxes/UsTaxes/tree/master/.github/workflows)

workflow jobs:

- ci: <https://github.com/daief/wakapi/actions/runs/2356033714>
- release: <https://github.com/daief/wakapi/actions/runs/2356038618>

I don't know `Run Mayhem for API` and why it fails(in theory I only copy the steps), so there's nothing that I can do to help.

**Comment by muety** [comment]
Thanks! This looks good to me!

Mayhem for API is a service that automatically penetration-tests your web API, given an OpenAPI document. It tries to find security flaws or get the application to crash. Was introduced in #372. It fails on your fork, because you don't have the required credentials configured in your project.

**Comment by daief** [comment]
> Thanks! This looks good to me!
> 
> Mayhem for API is a service that automatically penetration-tests your web API, given an OpenAPI document. It tries to find security flaws or get the application to crash. Was introduced in #372. It fails on your fork, because you don't have the required credentials configured in your project.

I get it now.

**Pull request merged**
