### PR TITLE
Fix wrong url in setup instructions

### PR DESCRIPTION
**Pull request by brorbw**
I've spent hours trying to figure out why I got a 401 and 404. The issues was that the help test on the index page is not the same as the one in the readme

### CODE REVIEW

**Comment by muety** [comment]
Are you sure this was the issue? Something similar was already discussed in https://github.com/muety/wakapi/issues/351, and both `/api` and `/api/heartbeat` should work equally. I'm using only `/api` myself.

**Comment by brorbw** [comment]
Quite sure. Changing the `api_url` in the config to `api/heartbeat` fixed the issue. Looking at the logs the server responds with `201` and `200` for request on `api/heartbeat` where it responded with `404` and `401` for the `api` endpoint.

**Comment by brorbw** [comment]
Too add to that. Inconsistencies smells a bit.

**Comment by muety** [comment]
Can you please try to do [this](https://github.com/muety/wakapi/issues/351#issuecomment-1093016016) and see if you get 404's then? 

Also, which version of `wakatime-cli` are you running?

**Comment by muety** [comment]
Good to hear. Yeah, the legacy CLI was stricter with regard to API URL paths.

**Pull request closed without merging**
