### PR TITLE
Persistent summary time interval

### LINKED ISSUE #391: Add an option to choose which timeframe should be displayed by default
Add an option, either in the web interface (it could be an option different for each user or the admin choose it) or in the environment variable. And allow to  choose which timeframe should be displayed by default.
For exemple always display this week instead of the current day.

### PR DESCRIPTION
**Pull request by Daste745**
These changes allow the back-end code to read a `wakapi_summary_interval` cookie and use it when the `interval` and `from` query params are missing.

Unfortunately, I didn't manage to send back a `Set-Cookie` header to persist the data on client-side, so some help here would be appreciated.

Closes #391.

### CODE REVIEW

**Comment by muety** [comment]
Thanks for this contribution! Looks good so far :+1: For setting a cookie, check the `ResponseWriter`'s [`SetCookie()`](https://pkg.go.dev/net/http#SetCookie) method. Hope that helps!

**Comment by muety** [comment]
Hey @Daste745, any updates on this?

**Comment by Daste745** [comment]
Yes, sorry, I've been focusing on other things lately, so I didn't have much time to work on this PR 😔. I'll finish it as soon as I find some time.

**Comment by muety** [comment]
No worries :+1:

**Comment by Daste745** [comment]
Alright, the response should now contain a `Set-Cookie` header with the used summary. It only sets the header if an explicit summary interval query param was provided.

**Comment by muety** [comment]
While testing this before having looked at the code, I got confused for a second, because the URL in the summary page didn't match what was actually shown on the page anymore. For example, if you select `month` interval, then move to a different page and get back to the summaries page, it will correctly show the month-data, but the URL will be just `/summary`, instead of `/summary?interval=month`. This would result in ambiguity, e.g. when wanting to share the current view by link.

Technically, your implementation works and I highly appreciate your contribution! But I think we can get this even a little cleaner, still. 

You added a bit of logic to check the cookie from inside the client-side JavaScript code and accordingly set the interval. What you could do now - in order to fix the above URL issue - is to also update `window.location.search` from the JavaScript accordingly. But I think there is a cleaner way even.

I propose to actually make this a "backend-only" change, i.e. keep the JavaScript out entirely. The process would look like this: 
1. Server receives request at `/summary`
2. It checks if `interval` URL parameter is present and, if yes, shows the according summary
3. If not, it moves on to checking if that newly introduced cookie is present and, if, yes returns a redirect (see [here](https://github.com/muety/wakapi/blob/master/routes/login.go#L177) for an example) to `/summary?interval=<the-interval-from-the-cookie>`. This would jump the process back to (1), but this time, an `interval` param will be found in (2)
4. If no param and no cookie are present, `"today"` is used as a fallback, just like before

This might be a little less efficient from a technical perspective, because there is a redirect involved. But I think it's a lot cleaner and all previous interval-related logic can stay just as is.

Do you think that makes sense?

Sorry for requesting change here! I'm aware that this is probably a bit picky, especially since your current code works perfectly fine. But I'd still like to include this change. No stress doing so! 

Thank you! :pray:

**Comment by Daste745** [comment]
Hi, thanks for the review!

I aggree on your points here, the current implementation introduces ambiguity, which is not always desirable. I like the redirect approach. We could even apply that to the `/` -> `/summary` redirect and go directly to `/summary?interval=<cookie_interval_if_exists>`. 

Regarding the perfomance, if we redirect early enough, it shouldn't be very noticeable, as an empty response with a redirect should be very small and quick on the client side. If this proves to be false, we could also use the [History.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) browser API, although I don't think this will be needed.


> Sorry for requesting change here! I'm aware that this is probably a bit picky, especially since your current code works perfectly fine. But I'd still like to include this change. No stress doing so!

No stress with that, I'll make the changes. Thanks for the example, it'll make it easier for me!

**Comment by Daste745** [comment]
Hi, I updated the logic to redirect to a correct summary url (with an `interval` query param) when it encounters a `/summary` request without the `interval` param and the `wakapi_summary_interval` cookie is set.

I also removed the (now unnecessary) front-end logic, which read the cookie value, from the time picker and summary page's `getCurrentInterval` function.

Sorry this took so long, I hope it's not an issue. 😅

**Comment by muety** [comment]
Awesome contribution, thanks a lot! :raised_hands:

**Pull request merged**
