### PR TITLE
Mobile Responsive

### PR DESCRIPTION
**Pull request by Milopadma**
### Whats changed
Updated ```summary.tpl.html``` tailwind classes to better support mobile views and be more responsive.

### CODE REVIEW

**Comment by muety** [comment]
Thanks for this contribution! However, things look a bit weird in desktop view.

Screen Shot 2024-09-24 at 08 55 05

**Comment by Milopadma** [comment]
### Mobile
image

### Tablet
image


### Desktop
image

**Comment by muety** [comment]
Still didn't look right for me, but found the issue. You'll have to run the following command after changing styles, since they are generated statically:

```bash
yarn build
yarn build:all:compress
```

It's not very well documented, so no worries for missing that part.

However, for iPad portrait mode view, the dashboard looks a bot too squeezed in my opinion. Perhaps wrap even a bit earlier or so? What do you think? 

image

**Comment by Milopadma** [comment]
oh thanks for that.

hmm, i think i agree, it does look cramped. how about this?
image

**Comment by Milopadma** [comment]
Lets adjust the KPI spacing as well..

###Mobile
image


###Tablet
image


###Desktop
image

**Comment by muety** [comment]
Love it! Thank you :+1:

Only thing still missing in terms of responsiveness is the settings page, I think. However, it would probably quite a hassle to get it mobile-friendly, while there's only little benefit to the user. Having dashboard, leaderboard and projects make look good on small screens is way more important anyway. 

Relates to #137.

**Comment by Milopadma** [comment]
> Love it! Thank you 👍
> 
> Only thing still missing in terms of responsiveness is the settings page, I think. However, it would probably quite a hassle to get it mobile-friendly, while there's only little benefit to the user. Having dashboard, leaderboard and projects make look good on small screens is way more important anyway.
> 
> Relates to #137.

Thanks!

From a quick skim, I think Leaderboard just needs a few spacing and text size adjustments for small screens, and Projects already look pretty good to me. Settings too, just needs a few spacing and text size adjustments. When I have time I can try and dig into it.

**Pull request merged**
